import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';
import 'bootstrap/dist/css/bootstrap.css';

import styles from '../styles/Landingpage.module.css';
import Navbar from '../components/nav/index';
import Footer from '../components/footer/index';
import Card from '../components/cardLandingpage/index';

const Landingpage = () => {
  return (
    <>
      <Head>
        <title>Landingpage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <div className={`container-fluid ${styles.container}`}>
        <div className={`row ${styles}`}>
          <section className={`row ${styles.section1}`}>
            <div className="col-1"></div>
            {/* ---------Left---------- */}
            <div className={`col-5 ${styles.divLeft1}`}>
              <div className={`row ${styles.mainLeft1}`}>
                <div className={styles.title1}>
                  <h3>Talenta terbaik negri untuk perubahan revolusi 4.0</h3>
                </div>
                <div className={styles.loream1}>
                  Lorem ipsum, dolor sit amet consectetur adipisicing elit. Qui, consequuntur, alias debitis nisi fuga
                  voluptas.
                </div>
                <div className={`${styles}`}>
                  <Link href={`/home`}>
                    <button className={styles.buttonSearch}>
                      <div>Mulai Dari Sekarang</div>
                    </button>
                  </Link>
                </div>
              </div>
            </div>
            {/* -----------------Right--------------- */}
            <div className={`col-5 ${styles.divRight1}`}>
              <div className={styles.mainRigh1}>
                <div className={styles.background1}></div>
                <div className={styles.divImage1}>
                  <Image
                    className={styles.image1}
                    src="/b9de1e2e658498c339524384fbdc112d.jpg"
                    width={500}
                    height={430}
                  />
                </div>
              </div>
            </div>
            <div className="col-1"></div>
          </section>

          {/* ------------------section2------------------------ */}
          <section className={`row ${styles.section2}`}>
            <div className="col-1"></div>
            {/* -------left------ */}
            <div className={`col-5 ${styles.contentLeft}`}>
              <div className={styles.mainRigh1}>
                {/* <div className={styles.divSquare}></div> */}
                <div className={styles.background2}></div>
                <div className={styles.divImage2}>
                  <Image className={styles.image2} src="/landing2.jpg" width={400} height={320} />
                </div>
              </div>
            </div>

            {/* ------Right------- */}
            <div className={`col-5 ${styles.divLeft1}`}>
              <div className="row">
                <div className={styles.title2}>
                  <h3>Kenapa harus mencari tallent di peworld</h3>
                </div>
                <div className={styles.divList1}>
                  <div className={styles.checklist1}>
                    <Image className={styles} src="/checklist.png" width={15} height={15} />
                  </div>
                  <div>Lorem ipsum dolor sit amet.</div>
                </div>
                <div className={styles.divList1}>
                  <div className={styles.checklist1}>
                    <Image className={styles} src="/checklist.png" width={15} height={15} />
                  </div>
                  <div>Lorem ipsum dolor sit amet.</div>
                </div>
                <div className={styles.divList1}>
                  <div className={styles.checklist1}>
                    <Image className={styles} src="/checklist.png" width={15} height={15} />
                  </div>
                  <div>Lorem ipsum dolor sit amet.</div>
                </div>
                <div className={styles.divList1}>
                  <div className={styles.checklist1}>
                    <Image className={styles} src="/checklist.png" width={15} height={15} />
                  </div>
                  <div>Lorem ipsum dolor sit amet.</div>
                </div>
              </div>
            </div>
            <div className="col-1"></div>
          </section>

          {/* ------------------section3------------------------ */}
          <section className={`row ${styles.section3}`}>
            <div className="col-1"></div>
            {/* -------left------ */}
            <div className={`col-5 ${styles.leftContent3}`}>
              <div className={styles.divTitle3}>
                <h3>Skill Tallent</h3>
              </div>
              <div className={styles.divLorem}>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. In euismod ipsum et dui rhoncus auctor.
              </div>
              <div className={styles.divList3}>
                <div style={{ marginRight: '100px' }}>
                  <div className={styles.divList1}>
                    <div className={styles.checklist1}>
                      <Image className={styles} src="/checkyellow.png" width={15} height={15} />
                    </div>
                    <div>Java</div>
                  </div>
                  <div className={styles.divList1}>
                    <div className={styles.checklist1}>
                      <Image className={styles} src="/checkyellow.png" width={15} height={15} />
                    </div>
                    <div>Kotlin</div>
                  </div>
                  <div className={styles.divList1}>
                    <div className={styles.checklist1}>
                      <Image className={styles} src="/checkyellow.png" width={15} height={15} />
                    </div>
                    <div>PHP</div>
                  </div>
                  <div className={styles.divList1}>
                    <div className={styles.checklist1}>
                      <Image className={styles} src="/checkyellow.png" width={15} height={15} />
                    </div>
                    <div>Javascript</div>
                  </div>
                </div>
                <div>
                  <div className={styles.divList1}>
                    <div className={styles.checklist1}>
                      <Image className={styles} src="/checkyellow.png" width={15} height={15} />
                    </div>
                    <div>Golang</div>
                  </div>
                  <div className={styles.divList1}>
                    <div className={styles.checklist1}>
                      <Image className={styles} src="/checkyellow.png" width={15} height={15} />
                    </div>
                    <div>C++</div>
                  </div>
                  <div className={styles.divList1}>
                    <div className={styles.checklist1}>
                      <Image className={styles} src="/checkyellow.png" width={15} height={15} />
                    </div>
                    <div>Ruby</div>
                  </div>
                  <div className={styles.divList1}>
                    <div className={styles.checklist1}>
                      <Image className={styles} src="/checkyellow.png" width={15} height={15} />
                    </div>
                    <div>10+ Bahasa Lainnya</div>
                  </div>
                </div>
              </div>
            </div>

            {/* ------Right------- */}
            <div className={`col-5 ${styles.contentSection3}`}>
              <div className={styles.mainRigh1}>
                {/* <div className={styles.divSquare}></div> */}
                <div className={styles.background3}></div>
                <div className={styles.divImage3}>
                  <Image className={styles.image3} src="/landing3.jpg" width={470} height={330} />
                </div>
              </div>
            </div>
            <div className="col-1"></div>
          </section>

          {/* ------------------section4------------------------ */}
          <section className={`row ${styles.section4}`}>
            <div className="col-1"></div>
            {/* -------main------ */}
            <div className="col-10">
              <div className={styles.title4}>
                <h3>Their opinion about peworld</h3>
              </div>
              <div className={styles.divCardUser}>
                <Card />
                <Card />
                <Card />
              </div>
            </div>
            <div className="col-1"></div>
          </section>

          {/* ------------------section------------------------ */}
          <section className={`row`}>
            <div className="col-1"></div>
            <div className="col-10"></div>
            <div className="col-1"></div>
          </section>
        </div>
      </div>

      <Footer />
    </>
  );
};

export default Landingpage;
